#
#Wed May 13 16:57:19 CLT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--incognito, start-maximized, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-access-check, disable-infobars, --incognito, start-maximized, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-access-check, disable-infobars, remote-allow-origins\=*], excludeSwitches\=[enable-automation, load-extension], extensions\=[], prefs\={default_content_settings.popups\=0, password_manager_enabled\=false, credentials_enable_service\=false, default_content_settings.geolocation\=2}}
